module.exports = {
  arrowParens: 'always',
  bracketSpacing: true,
  endOfLine: 'lf',
  htmlWhitespaceSensitivity: 'css',
  insertPragma: false,
  bracketSameLine: false,
  jsxSingleQuote: false,
  printWidth: 80,
  proseWrap: 'preserve',
  quoteProps: 'as-needed',
  requirePragma: false,
  semi: false,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'es5',
  useTabs: false,
  plugins: ['@trivago/prettier-plugin-sort-imports'],
  importOrder: [
    '^react$',
    '^react-(.*)$',
    '<THIRD_PARTY_MODULES>',
    '^base',
    '^form',
    '^modules',
    '^sections',
    '^utils',
    '^types',
    '^[./]',
    '^.+\\.(s?css)$',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
}
